Added github authentication to program.cs
ITU-BDSA23-GROUP4/Chirp pull request #120
Opened 2023-11-07 13:50 UTC by Lukan707

"

2023-11-07 21:17 UTC, Faberen approved these changes
Very Nice good jkob

2023-11-08 11:15 UTC, annahj1006 requested changes
I think removing the fluent Assertions package will cause great problems, since they are used in every test, removing the usings will not work? Since i can see you made no changes to the tests itself, they do not run, any of them. I have checked the tests in your branch, and none of them work without the package!

2023-11-08 11:15 UTC, annahj1006 commented on src/Chirp.Razor/Program.cs
What exactly is going on here? I feel like some information is missing, like small comments or something? What does he addAuthentication consist of? What is the stringToCheck?

2023-11-08 11:15 UTC, annahj1006 commented on test/Chirp.Infrastructure.Tests/AuthorRepositoryUnitTests.cs
Have you tested that it still works without fluentAssertions?? Since the tests depends on using those in the Assert and Act parts? 
This can be a problem

2023-11-08 11:35 UTC, Lukan707 commented on test/Chirp.Infrastructure.Tests/AuthorRepositoryUnitTests.cs
In the current state of the code, the using is unused, an as you can see, all tests passes.
If the later pull request depends on it, it will still be in the code, or else the test and code won't compile,
and git will treat it as a addition.

Therefor there will be no problem.

2023-11-08 13:45 UTC, Lukan707 commented on src/Chirp.Razor/Program.cs
Thank you Anna.

Your comment made me think about why we added it in the first place, and made me realise we didn't this functionality add all.

The methodcalls add authentication middleware, which we don't need, since EasyAuth contains the middleware, but outside of the scope of our application code, just inside the same Azure Contianer.

Thanks for pointing it out, as well as giving me a reason, to study more carefully the specifics about theese methods calls.

Note: We keep the app.Useauthorization, since the EasyAuth does not provide functionality for authorization.

2023-11-08 13:50 UTC, Lukan707 commented
The remove fluent assertions package is not removed, but just moved into GlobalUsings.cs as a global using statement for that project.

2023-11-08 14:32 UTC, annahj1006 approved these changes

2023-11-08 22:15 UTC, merged