Corrected CheepDTO
ITU-BDSA23-GROUP4/Chirp pull request #228
Opened 2023-12-07 15:26 UTC by Lukan707

The CheepDTO has been corrected, such that it contains and id for the cheep and not the author.
Also the attribute Name has been renamed to AuthorName, to clarify that it is the name of the auhor of the cheep.

2023-12-07 23:34 UTC, SkarpKat commented on src/Chirp.Infrastructure/CheepRepository.cs
> +                    CheepId = new Guid(),
I think that this is not the way you use Guid. You should use Guid.NewGuid() instead of new Guid().

2023-12-07 23:35 UTC, SkarpKat commented on test/Chirp.Infrastructure.Tests/InMemoryDatabaseUnitTest.cs
> +            CheepId = new Guid(1, 0, 0, new byte[]{0,0,0,0,0,0,0,0}),
I think that this is not the way you use Guid. You should use Guid.NewGuid() instead of new Guid().

2023-12-07 23:35 UTC, SkarpKat commented on src/Chirp.Infrastructure/CheepRepository.cs
> +            CheepId = new Guid(),
I think that this is not the way you use Guid. You should use Guid.NewGuid() instead of new Guid().

2023-12-07 23:36 UTC, SkarpKat commented on test/Chirp.Infrastructure.Tests/RestrictedCheepsUnitTests.cs
> +            CheepId = new Guid(1, 0, 0, new byte[]{0,0,0,0,0,0,0,0}),
I think that this is not the way you use Guid. You should use Guid.NewGuid() instead of new Guid().

2023-12-07 23:36 UTC, SkarpKat commented on test/Chirp.Infrastructure.Tests/RestrictedCheepsUnitTests.cs
> +        cheeps.Should().Contain(c => c.CheepId == new Guid(1, 0, 0, new byte[]{0,0,0,0,0,0,0,0}) && c.Message == "This is a cheep for testing");
I think that this is not the way you use Guid. You should use Guid.NewGuid() instead of new Guid().

2023-12-07 23:37 UTC, SkarpKat requested changes
I think there needs to be some changes with the use of Guid other then that it looks good.

2023-12-08 01:13 UTC, Lukan707 commented
> I think there needs to be some changes with the use of Guid other then that it looks good.

Thanks for spotting this. It has now been resolved in commit 5ab5589

2023-12-08 12:34 UTC, Lukan707 commented on src/Chirp.Infrastructure/CheepRepository.cs
> +
Thank you for spotting this. It has now been resolved in commit 1a1d0f2

2023-12-08 12:37 UTC, AlbinoLoaf approved these changes

2023-12-08 12:37 UTC, SkarpKat approved these changes
Nice

2023-12-08 12:39 UTC, merged