Followed on my timeline
ITU-BDSA23-GROUP4/Chirp pull request #242
Opened 2023-12-12 16:51 UTC by Faberen

2023-12-12 18:42 UTC, AlbinoLoaf requested changes
Add

2023-12-12 18:42 UTC, AlbinoLoaf commented on src/Chirp.Infrastructure/CheepRepository.cs
> +        //Change later
Remove comment

2023-12-13 09:08 UTC, annahj1006 approved these changes
Some of them are quite large methods, perhabs add some more description for readability? Also one comment on line 334 is not complete?
Otherwise really nice work!

2023-12-17 19:56 UTC, Lukan707 commented on src/Chirp.Infrastructure/CheepRepository.cs
> +//     }
This has been resolved in commit 18e8b19.

@Marius it is okay to solve theese minimum effort fixes yourself, and just comment. I can also see that you are a co-author of this :)

2023-12-17 19:57 UTC, Lukan707 commented on src/Chirp.Infrastructure/CheepRepository.cs
> +
I belive this is evident from the code.

However I have commented in commit 18e8b19, what the two functions are used for :)

2023-12-17 20:05 UTC, Lukan707 commented
> Some of them are quite large methods, perhabs add some more description for readability? Also one comment on line 334 is not complete? Otherwise really nice work!

I am unable to find the comment you are reffering to. In which file is the incomplete comment placed in? 

I have added an issue regarding the comments on large methods: #247

2023-12-17 20:15 UTC, SkarpKat approved these changes

2023-12-17 20:17 UTC, Lukan707 approved these changes
Nice work @Faberen and @AlbinoLoaf

2023-12-17 20:35 UTC, AlbinoLoaf approved these changes

2023-12-17 20:41 UTC, merged