Moved folders to correct directory according to project description
ITU-BDSA23-GROUP4/Chirp pull request #289
Opened 2023-12-19 16:39 UTC by Faberen

2023-12-19 16:46 UTC, SkarpKat approved these changes

2023-12-19 17:10 UTC, Lukan707 requested changes
Just a detail, but why we are at it.<
The root folder for the report and documents should actually be called "docs" and not "Docs". I will quickly change this.

2023-12-19 17:23 UTC, Lukan707 commented
> Just a detail, but why we are at it.< The root folder for the report and documents should actually be called "docs" and not "Docs". I will quickly change this.

This has been resolved in commit 20863d6

2023-12-19 17:23 UTC, Lukan707 approved these changes

2023-12-19 17:51 UTC, AlbinoLoaf approved these changes

2023-12-20 10:19 UTC, Faberen commented
We will create a new pull request once everything is merged in to main as to make the merge conflicts easier ot dela with

2023-12-20 10:19 UTC, closed without merging