Created CheepDTO and made it usable across the program
ITU-BDSA23-GROUP4/Chirp pull request #63
Opened 2023-10-10 12:20 UTC by annahj1006

2023-10-10 12:27 UTC, Lukan707 requested changes
Nice work.

Since names are not unique, and we want to request cheeps by author, when clicking an author, how about we add the id to the DTO, so we can send it back we the get request from the client.

2023-10-10 12:35 UTC, Lukan707 approved these changes
Nice :)

2023-10-10 12:35 UTC, Lukan707 commented on src/Chirp.Razor/CheepContext.cs
> +    public required int CheepId { get; set; }
We might want to rename this to AuthorId, since it is the id of the author and not the id of the actual cheep.

2023-10-12 11:22 UTC, SkarpKat approved these changes
Nice

2023-10-12 11:22 UTC, AlbinoLoaf commented on src/Chirp.Razor/CheepContext.cs
> +    public ChirpDBContext() //Finds the current db in temp folder
Place the comment above the line that it pertains to

2023-10-12 11:22 UTC, AlbinoLoaf commented on src/Chirp.Razor/CheepRepository.cs
> +        //Creates a list of max 32 CheepDTO sorted by recent cheep
The Max is not made here reference the point of creation

2023-10-12 11:23 UTC, merged