Author repo
ITU-BDSA23-GROUP4/Chirp pull request #85
Opened 2023-10-13 19:27 UTC by SkarpKat

Added an Author repo with an author DTO and moved the AddAuthor method out of Cheep Repo and moved to Author Repo. Also added a GetAuthor method.

Please check the AuthorDTO since i'm not a master with DTO's

2023-10-15 08:19 UTC, annahj1006 requested changes

2023-10-15 08:19 UTC, annahj1006 commented on src/Chirp.Core/AuthorDTO.cs
We should probably have the author ID going with the DTO, like we updated with Cheeps

2023-10-16 09:28 UTC, Faberen approved these changes
Looks good to me

2023-10-16 14:45 UTC, annahj1006 approved these changes
Awesome

2023-10-16 15:24 UTC, merged